name: model_x0.deployment

depends:
  - SensingA.pipeline
  - PerceptionA.pipeline
  - PerceptionPipelineA.parameter_set

compute_units:
  - unit: main_ecu
    components:
      - component: sensor_pipeline_a
        element: SensingA.pipeline
        namespace: sensing
      - component: perception_pipeline_a
        element: PerceptionA.pipeline
        namespace: perception

connections:
  - from: sensor_pipeline_a.output.pointcloud
    to: perception_pipeline_a.input.pointcloud

parameter_sets:
  - name: perception_parameter_set_pipeline_a
    set: PerceptionPipelineA.parameter_set

parameter_connections:
  - from: perception_parameter_set_pipeline_a.*
    to: perception_pipeline_a.parameter.*
